# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
#' @useDynLib RCaN
NULL

fitCaN <- function(N, A, b, C, v, L, M, x0) {
    .Call('_RCaN_fitCaN', PACKAGE = 'RCaN', N, A, b, C, v, L, M, x0)
}

