usethis::use_package('shiny')
usethis::use_package("visNetwork")
usethis::use_package("RCaNmodel")
usethis::use_package("shinydashboardPlus")
usethis::use_package("htmltools")
usethis::use_package("spsComps")
usethis::use_package("shinydashboard")
usethis::use_package("shinyjs")
usethis::use_package("magrittr")
usethis::use_package("rlang")
usethis::use_package("stringr")
usethis::use_package("readxl")
usethis::use_package("openxlsx")

usethis::use_package("dplyr")
usethis::use_package("rhandsontable")
usethis::use_build_ignore("devtools_history.R")
usethis::use_package("datamods")
