# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Maven Basic Package

on:
  push:
    branches:
      - master
      - RCaNconstructor
  pull_request:
      - master
      - RCaNconstructor

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: 17.0.1
        distribution: 'temurin'
        cache: 'maven'
    - name: Build with Maven
      run: mvn -B clean package --file RCaNconstructor/pom.xml
