# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Maven Basic Package

on:
  workflow_dispatch:
    branches: [ master ]
  push:
    branches: [ master ]
    paths:
      - RCaNconstructor/**
    

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: 21.0.3
        distribution: 'temurin'
        cache: 'maven'
    - name: Build with Maven
      run: mvn -B clean package --file RCaNconstructor/pom.xml
