# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build Windows Installer

on:
  workflow_dispatch:
    branches: [ master ]
  push:
    branches: [ master ]
  paths:
    - RCaNconstructor/**

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Download Wix
      uses: i3h/download-release-asset@v1
      with:
        owner: wixtoolset
        repo: wix3
        tag: wix3112rtm
        file: wix311-binaries.zip
    - name: Decompress Wix
      uses: DuckSoft/extract-7z-action@v1.0
      with:
        pathSource: wix311-binaries.zip
        pathTarget: ./target/wix
    - name: Add Wix to Path
      run: echo "$HOME/target/wix" >> $GITHUB_PATH
    - name: Checkout code
      uses: rohmanngmbh/action-checkout-repo@v1.3.2
      with:
        lfs: true
        path: RCaNconstructor
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: 17.0.1
        distribution: 'temurin'
        cache: 'maven'
    - name: Build with Maven
      run: mvn -B clean install --file RCaNconstructor/pom.xml
    - name: Update Automatic Release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN}}"
        automatic_release_tag: "Windows-latest"
        prerelease: true
        title: "Windows Development Build"
        files: ./target/*.msi
