# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Maven Basic Package

on:
  push:
    branches: [ master ]
  paths:
    - RCaNconstructor/**
    

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: nschloe/action-cached-lfs-checkout@v1
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: 17.0.1
        distribution: 'temurin'
        cache: 'maven'
    - name: Build with Maven
      run: mvn -B clean package --file RCaNconstructor/pom.xml
